site_name: Glioblastoma Unsupervised Learning Investigation
site_description: TCGA Earned
site_author: Santiago López Cervantes


nav:
  - Home: index.md
  - Problem Statement: problem_statement.md
  - Exploratory Data Analysis: eda.ipynb
  - Feature Engineering: feature_engineering.ipynb
  - Model Construction and Result Interpretation: model_const_interpretation.ipynb
  - Discussion and Conclusion: conclusions_&_discussion.md

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - mkdocs-jupyter